import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6EDE2',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 50,
    paddingBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: '#F6EDE2',
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: 'Exo_700Bold',
    fontSize: 20,
    color: '#000',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImageSection: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 32,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 8,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FFF',
  },
  profileImagePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  changeImageButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#F6EDE2',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  removeImageButton: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageHintText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#666',
    marginTop: 8,
  },
  fieldGroup: {
    marginBottom: 24,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  label: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 14,
    color: '#000',
    marginBottom: 8,
  },
  labelHint: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#666',
  },
  input: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#000',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  textArea: {
    minHeight: 140,
  },
  inputDisabled: {
    backgroundColor: '#F3F3F3',
    color: '#999',
  },
  inputError: {
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  errorText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#FF6B35',
    marginTop: 4,
  },
  hintText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  fieldFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  characterCount: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#666',
  },
  saveButton: {
    backgroundColor: '#FF6B35',
    borderRadius: 28,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 16,
    color: '#FFF',
  },
  passwordSection: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  passwordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  passwordTitle: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 16,
    color: '#000',
  },
  changePasswordButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#FFE5DB',
  },
  changePasswordButtonText: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 13,
    color: '#FF6B35',
  },
  passwordFields: {
    marginTop: 4,
  },
  passwordInput: {
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontFamily: 'Exo_400Regular',
    fontSize: 15,
    color: '#000',
    marginBottom: 10,
  },
  passwordActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 8,
  },
  passwordCancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 8,
  },
  passwordCancelText: {
    fontFamily: 'Exo_500Medium',
    color: '#6B7280',
    fontSize: 14,
  },
  passwordSaveButton: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
  },
  passwordSaveButtonDisabled: {
    backgroundColor: '#F9A885',
  },
  passwordSaveButtonText: {
    fontFamily: 'Exo_600SemiBold',
    color: '#FFF',
    fontSize: 14,
  },
});

