import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF1E6',
    paddingTop: 64,
    paddingHorizontal: 24,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 120,
  },
  contentWrap: {
    flexGrow: 1,
  },
  title: {
    fontFamily: 'Exo_700Bold',
    fontSize: 28,
    color: '#121212',
  },
  subtitle: {
    marginTop: 8,
    fontFamily: 'Exo_400Regular',
    fontSize: 14,
    color: '#2b2b2b',
    opacity: 0.9,
  },
  fieldGroup: {
    marginTop: 28,
  },
  label: {
    fontFamily: 'Exo_500Medium',
    fontSize: 14,
    color: '#1a1a1a',
    marginBottom: 8,
  },
  input: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    paddingVertical: 6,
    color: '#0f0f0f',
  },
  underline: {
    height: 1,
    backgroundColor: '#1f1f1f',
    opacity: 0.9,
  },
  rowBetween: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#1f1f1f',
    marginRight: 10,
    backgroundColor: 'transparent',
  },
  rememberText: {
    fontFamily: 'Exo_400Regular',
    color: '#1a1a1a',
  },
  forgot: {
    fontFamily: 'Exo_400Regular_Italic',
    color: '#111',
    opacity: 0.9,
    fontSize: 12,
  },
  primaryButton: {
    marginTop: 28,
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingVertical: 14,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  primaryButtonDisabled: {
    backgroundColor: '#E0E0E0',
    shadowOpacity: 0.05,
    elevation: 2,
  },
  primaryButtonText: {
    fontFamily: 'Exo_700Bold',
    color: '#111',
    fontSize: 18,
  },
  primaryButtonTextDisabled: {
    color: '#999',
  },
  bottomRow: {
    position: 'absolute',
    bottom: 36,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomMuted: {
    fontFamily: 'Exo_400Regular',
    color: '#2b2b2b',
    opacity: 0.9,
    fontSize: 13,
  },
  bottomLink: {
    fontFamily: 'Exo_700Bold',
    color: '#000',
    fontSize: 13,
  },
  inputError: {
    color: '#FF6B35',
  },
  underlineError: {
    backgroundColor: '#FF6B35',
    opacity: 1,
  },
  errorText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#FF6B35',
    marginTop: 4,
  },
  errorContainer: {
    marginTop: 12,
    padding: 12,
    backgroundColor: '#FFE5E5',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  dividerContainer: {
    marginTop: 28,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  dividerText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 14,
    color: '#666',
    marginHorizontal: 12,
  },
  googleButton: {
    marginTop: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  googleButtonDisabled: {
    opacity: 0.6,
  },
  googleIcon: {
    marginRight: 12,
  },
  googleButtonText: {
    fontFamily: 'Exo_600SemiBold',
    color: '#000',
    fontSize: 16,
  },
});

