import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6EDE2',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: '#F6EDE2',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontFamily: 'Exo_700Bold',
    fontSize: 24,
    color: '#222',
    flex: 1,
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 200,
    paddingTop: 8,
    flexGrow: 1,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  label: {
    fontFamily: 'Exo_700Bold',
    fontSize: 16,
    color: '#222',
    marginBottom: 12,
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  uploadButtonText: {
    fontFamily: 'Exo_500Medium',
    fontSize: 16,
    color: '#222',
    marginLeft: 8,
  },
  input: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#222',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  priceInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  pesoSymbol: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#222',
    marginRight: 8,
  },
  priceInput: {
    flex: 1,
    paddingVertical: 14,
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#222',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: -8,
  },
  categoryPill: {
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  categoryPillSelected: {
    backgroundColor: '#666',
  },
  categoryText: {
    fontFamily: 'Exo_500Medium',
    fontSize: 14,
    color: '#222',
  },
  categoryTextSelected: {
    color: '#FFF',
  },
  flexRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: -8,
  },
  flexPill: {
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  flexPillSelected: {
    backgroundColor: '#666',
  },
  flexText: {
    fontFamily: 'Exo_500Medium',
    fontSize: 13,
    color: '#222',
  },
  flexTextSelected: {
    color: '#FFF',
  },
  conditionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: -8,
  },
  conditionPill: {
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  conditionPillSelected: {
    backgroundColor: '#666',
  },
  conditionText: {
    fontFamily: 'Exo_500Medium',
    fontSize: 14,
    color: '#222',
  },
  conditionTextSelected: {
    color: '#FFF',
  },
  descriptionInput: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#222',
    minHeight: 120,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  charCount: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#999',
    textAlign: 'right',
    marginTop: 6,
  },
  locationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  locationIcon: {
    marginRight: 8,
  },
  locationInput: {
    flex: 1,
    paddingVertical: 14,
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#222',
  },
  bottomSpacer: {
    height: 40,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#F6EDE2',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  postButton: {
    backgroundColor: '#FFF',
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  postButtonDisabled: {
    backgroundColor: '#E0E0E0',
    shadowOpacity: 0.05,
    elevation: 2,
  },
  postButtonText: {
    fontFamily: 'Exo_700Bold',
    fontSize: 18,
    color: '#222',
  },
  postButtonTextDisabled: {
    color: '#999',
  },
  disabledHint: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
    marginTop: 8,
  },
});

