import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6EDE2',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 50,
  },
  heroCard: {
    backgroundColor: '#FF6B35',
    borderRadius: 32,
    padding: 28,
    marginBottom: 28,
    shadowColor: '#FF6B35',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  title: {
    fontFamily: 'Exo_700Bold',
    fontSize: 30,
    color: '#FFF',
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#FFF',
    opacity: 0.9,
  },
  formCard: {
    backgroundColor: '#FFF',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  fieldGroup: {
    marginTop: 20,
  },
  label: {
    fontFamily: 'Exo_500Medium',
    fontSize: 14,
    color: '#111827',
    marginBottom: 8,
  },
  input: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    color: '#111',
  },
  primaryButton: {
    marginTop: 24,
    backgroundColor: '#111827',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    fontFamily: 'Exo_700Bold',
    color: '#FFF',
    fontSize: 16,
  },
  errorText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#FF6B35',
    marginTop: 6,
  },
  errorContainer: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#FFF1ED',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFB199',
  },
  dividerContainer: {
    marginTop: 24,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  dividerText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 13,
    color: '#6B7280',
    marginHorizontal: 12,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    paddingVertical: 14,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  googleButtonDisabled: {
    opacity: 0.6,
  },
  googleIcon: {
    marginRight: 12,
  },
  googleButtonText: {
    fontFamily: 'Exo_600SemiBold',
    color: '#111',
    fontSize: 15,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 26,
  },
  bottomMuted: {
    fontFamily: 'Exo_400Regular',
    color: '#4B5563',
    fontSize: 14,
  },
  bottomLink: {
    fontFamily: 'Exo_600SemiBold',
    color: '#FF6B35',
    fontSize: 14,
  },
  inputError: {
    borderColor: '#FF6B35',
    backgroundColor: '#FFF6F2',
  },
});

