import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6EDE2',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 50,
    paddingBottom: 12,
    paddingHorizontal: 20,
    zIndex: 1000,
    elevation: 1000,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    padding: 8,
    minWidth: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
    paddingTop: 120,
    backgroundColor: 'transparent',
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  profilePhotoContainer: {
    marginBottom: 12,
  },
  profilePhoto: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    overflow: 'hidden',
  },
  username: {
    fontFamily: 'Exo_700Bold',
    fontSize: 24,
    color: '#000',
    marginBottom: 12,
  },
  statsContainer: {
    alignItems: 'center',
    marginBottom: 12,
  },
  statText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  followButton: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 24,
    backgroundColor: '#FF6B35',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followButtonActive: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  followButtonText: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  followButtonTextActive: {
    color: '#111827',
  },
  reputationContainer: {
    alignItems: 'center',
    marginTop: 8,
  },
  reputationText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 13,
    color: '#666',
    marginBottom: 6,
  },
  starsContainer: {
    flexDirection: 'row',
  },
  reputationSubtext: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#888',
    marginTop: 6,
  },
  bioSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
    alignItems: 'center',
  },
  bioText: {
    fontFamily: 'Exo_400Regular_Italic',
    fontSize: 15,
    color: '#333',
    textAlign: 'center',
    lineHeight: 22,
  },
  bioPlaceholderText: {
    fontFamily: 'Exo_400Regular',
    color: '#888',
  },
  searchSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Exo_400Regular',
    fontSize: 14,
    color: '#000',
  },
  filterButtons: {
    flexDirection: 'row',
  },
  filterButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  filterButtonText: {
    fontFamily: 'Exo_500Medium',
    fontSize: 14,
    color: '#000',
  },
  listingsSection: {
    paddingHorizontal: 20,
  },
  reviewsSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
    backgroundColor: 'transparent',
  },
  reviewsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  reviewsTitle: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 16,
    color: '#111',
  },
  reviewsLink: {
    fontFamily: 'Exo_500Medium',
    color: '#FF6B35',
    fontSize: 14,
  },
  reviewCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  reviewAuthor: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 14,
    color: '#111',
  },
  reviewDate: {
    fontFamily: 'Exo_400Regular',
    fontSize: 12,
    color: '#9CA3AF',
  },
  reviewRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  reviewRatingText: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 12,
    marginLeft: 4,
    color: '#92400E',
  },
  reviewText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 13,
    color: '#333',
    lineHeight: 20,
  },
  reviewTextMuted: {
    fontFamily: 'Exo_400Regular_Italic',
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  productCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 12,
    width: '48%',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  cardLeft: {
    marginRight: '2%',
  },
  cardRight: {
    marginLeft: '2%',
  },
  productImage: {
    width: '100%',
    height: 120,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: '#F5F5F5',
  },
  productImagePlaceholder: {
    width: '100%',
    height: 120,
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  imagePlaceholderText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 10,
    color: '#666',
    textAlign: 'center',
    marginTop: 4,
  },
  productName: {
    fontFamily: 'Exo_600SemiBold',
    fontSize: 12,
    color: '#000',
    marginBottom: 6,
  },
  productPrice: {
    fontFamily: 'Exo_700Bold',
    fontSize: 14,
    color: '#000',
    marginBottom: 8,
  },
  sellerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sellerAvatar: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sellerName: {
    fontFamily: 'Exo_400Regular',
    fontSize: 10,
    color: '#666',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingVertical: 12,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navLabel: {
    fontFamily: 'Exo_400Regular',
    fontSize: 10,
    color: '#999',
    marginTop: 4,
  },
  navLabelActive: {
    fontFamily: 'Exo_700Bold',
    fontSize: 10,
    color: '#000',
    marginTop: 4,
  },
  emptyState: {
    width: '100%',
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyStateText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#999',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlayBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 20,
    width: '80%',
    maxWidth: 300,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 10,
    zIndex: 1,
  },
  modalTitle: {
    fontFamily: 'Exo_700Bold',
    fontSize: 18,
    color: '#000',
    marginBottom: 16,
  },
  modalOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  modalOptionSelected: {
    backgroundColor: '#F6EDE2',
  },
  modalOptionText: {
    fontFamily: 'Exo_400Regular',
    fontSize: 16,
    color: '#000',
  },
  modalOptionTextSelected: {
    fontFamily: 'Exo_600SemiBold',
    color: '#FF6B35',
  },
});


