export const PHILIPPINE_CITIES_BY_REGION = {
  NCR: [
    'Caloocan',
    'Las Pinas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Paranaque',
    'Pasay',
    'Pasig',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  CAR: [
    'Baguio',
    'Tabuk',
  ],
  'Region I': [
    'Alaminos',
    'Batac',
    'Candon',
    'Dagupan',
    'Laoag',
    'San Carlos (Pangasinan)',
    'San Fernando (La Union)',
    'Urdaneta',
    'Vigan',
  ],
  'Region II': [
    'Cauayan',
    'Ilagan',
    'Santiago',
    'Tuguegarao',
  ],
  'Region III': [
    'Angeles',
    'Balanga',
    'Cabanatuan',
    'Gapan',
    'Mabalacat',
    'Malolos',
    'Meycauayan',
    'Munoz',
    'Olongapo',
    'Palayan',
    'San Fernando (Pampanga)',
    'San Jose del Monte',
    'San Jose (Nueva Ecija)',
    'Tarlac City',
  ],
  'Region IV-A': [
    'Antipolo',
    'Bacoor',
    'Batangas City',
    'Binan',
    'Calamba',
    'Cavite City',
    'Dasmarinas',
    'General Trias',
    'Imus',
    'Lipa',
    'Lucena',
    'San Pablo',
    'San Pedro',
    'Santa Rosa',
    'Santo Tomas',
    'Tagaytay',
    'Tanauan',
    'Trece Martires',
  ],
  'Region IV-B': [
    'Calapan',
    'Puerto Princesa',
  ],
  'Region V': [
    'Iriga',
    'Legazpi',
    'Ligao',
    'Masbate City',
    'Naga',
    'Sorsogon City',
    'Tabaco',
  ],
  'Region VI': [
    'Bacolod',
    'Bago',
    'Cadiz',
    'Escalante',
    'Himamaylan',
    'Iloilo City',
    'Kabankalan',
    'La Carlota',
    'Passi',
    'Roxas',
    'Sagay',
    'San Carlos (Negros Occidental)',
    'Silay',
    'Sipalay',
    'Talisay (Negros Occidental)',
    'Victorias',
  ],
  'Region VII': [
    'Bais',
    'Bayawan',
    'Bogo',
    'Carcar',
    'Cebu City',
    'Danao',
    'Dumaguete',
    'Lapu-Lapu',
    'Mandaue',
    'Naga (Cebu)',
    'Tagbilaran',
    'Talisay (Cebu)',
    'Toledo',
  ],
  'Region VIII': [
    'Baybay',
    'Borongan',
    'Calbayog',
    'Catbalogan',
    'Maasin',
    'Ormoc',
    'Tacloban',
  ],
  'Region IX': [
    'Dapitan',
    'Dipolog',
    'Isabela (Basilan)',
    'Pagadian',
    'Zamboanga City',
  ],
  'Region X': [
    'Cagayan de Oro',
    'El Salvador',
    'Gingoog',
    'Iligan',
    'Malaybalay',
    'Oroquieta',
    'Ozamiz',
    'Tangub',
    'Valencia (Bukidnon)',
  ],
  'Region XI': [
    'Davao City',
    'Digos',
    'Mati',
    'Panabo',
    'Samal',
    'Tagum',
  ],
  'Region XII': [
    'General Santos',
    'Kidapawan',
    'Koronadal',
    'Tacurong',
  ],
  'Region XIII': [
    'Bayugan',
    'Bislig',
    'Butuan',
    'Cabadbaran',
    'Surigao City',
    'Tandag',
  ],
  BARMM: [
    'Cotabato City',
    'Lamitan',
    'Marawi',
  ],
};

export const PHILIPPINE_LOCATION_OPTIONS = Object.entries(PHILIPPINE_CITIES_BY_REGION).flatMap(
  ([region, cities]) => cities.map((city) => `${region}, ${city}`)
);
